#!/bin/sh

path=/opt/autodesk/maya/bin
pythonhome=$path/..
export PYTHONHOME=$pythonhome
export LD_LIBRARY_PATH=$path/../lib:$LD_LIBRARY_PATH
export MAYA_LOCATION=$path/..
export QT_PLUGIN_PATH=$path/../qt-plugins
export PYTHONPATH=$PYTHONPATH:/opt/rh/devtoolset-7/root/usr/lib64/python2.7/site-packages:/usr/lib/python2.7/site-packages/

exec /usr/bin/bpython -i standalone.py
